# Generated by Django 6.0.3 on 2026-03-22 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Categoría de Gasto',
                'verbose_name_plural': 'Categorías de Gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre clasificación')),
                ('orden', models.IntegerField(default=1, verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, verbose_name='Activa')),
            ],
            options={
                'verbose_name': 'Clasificación',
                'verbose_name_plural': 'Clasificaciones',
                'ordering': ['producto', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='LiquidacionInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Liquidación de Inventario',
                'verbose_name_plural': 'Liquidaciones de Inventario',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('tiene_descuento_gobierno', models.BooleanField(default=False, verbose_name='Descuento gobierno')),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='% Descuento gobierno')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('direccion', models.TextField(blank=True, verbose_name='Dirección')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='VentaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Venta en Efectivo',
                'verbose_name_plural': 'Ventas en Efectivo',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripción')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoriagasto', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_ingresado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg ingresado')),
                ('kg_vendido', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg vendido')),
                ('kg_restante', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg restante')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por kg')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clasificacion', verbose_name='Clasificación')),
                ('liquidacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.liquidacioninventario', verbose_name='Liquidación')),
            ],
            options={
                'verbose_name': 'Detalle de Inventario',
                'verbose_name_plural': 'Detalles de Inventario',
            },
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='core.producto', verbose_name='Producto'),
        ),
        migrations.CreateModel(
            name='VentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas', to='core.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta a Crédito',
                'verbose_name_plural': 'Ventas a Crédito',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PagoVentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Medio de pago')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='core.ventacredito', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pagos de Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleVentaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_vendido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg vendido')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por kg')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clasificacion', verbose_name='Clasificación')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ventacredito', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
            },
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.producto', verbose_name='Producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='viajes', to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Viaje',
                'verbose_name_plural': 'Viajes',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PagoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto')),
                ('medio_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('cheque', 'Cheque')], max_length=20, verbose_name='Medio de pago')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_proveedor', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Pago a Proveedor',
                'verbose_name_plural': 'Pagos a Proveedores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='LoteClasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por kg')),
                ('kg_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg bruto (con canastillas)')),
                ('cantidad_canastillas_negras', models.IntegerField(default=0, verbose_name='Canastillas negras')),
                ('cantidad_canastillas_colores', models.IntegerField(default=0, verbose_name='Canastillas de colores')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.clasificacion', verbose_name='Clasificación')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Lote por Clasificación',
                'verbose_name_plural': 'Lotes por Clasificación',
            },
        ),
    ]
