# Generated by Django 6.0.2 on 2026-03-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacredito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_credito', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ventaefectivo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_efectivo', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='ventaefectivo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_efectivo', to='core.producto', verbose_name='Producto'),
        ),
    ]
