# Generated by Django 6.0.2 on 2026-03-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ventacredito_producto_ventaefectivo_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaefectivo',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventas_efectivo', to='core.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='ventaefectivo',
            name='kg_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg vendido'),
        ),
        migrations.AddField(
            model_name='ventaefectivo',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por kg'),
        ),
        migrations.AlterField(
            model_name='ventaefectivo',
            name='descripcion',
            field=models.CharField(blank=True, max_length=300, verbose_name='Descripción'),
        ),
    ]
