# Generated by Django 6.0.2 on 2026-04-02 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ventaefectivo_clasificacion_ventaefectivo_kg_vendido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventacredito',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='ventacredito',
            name='fecha',
            field=models.DateField(verbose_name='Fecha de venta'),
        ),
    ]
