# Generated by Django 6.0.2 on 2026-04-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ventacredito_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteclasificacion',
            name='cantidad_canastillas_colores',
        ),
        migrations.RemoveField(
            model_name='loteclasificacion',
            name='cantidad_canastillas_negras',
        ),
        migrations.RemoveField(
            model_name='loteclasificacion',
            name='kg_bruto',
        ),
        migrations.AddField(
            model_name='loteclasificacion',
            name='kg_neto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Neto Clasificado'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='cantidad_canastillas_colores',
            field=models.IntegerField(default=0, verbose_name='Canastillas Colores'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='cantidad_canastillas_negras',
            field=models.IntegerField(default=0, verbose_name='Canastillas Negras'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='kg_bruto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Bruto Recibido'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='kg_podridos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Podridos / Rechazo'),
        ),
    ]
