# Generated by Django 6.0.2 on 2026-04-02 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_loteclasificacion_cantidad_canastillas_colores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loteclasificacion',
            name='precio_por_kg',
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='stock_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Stock (Kg)'),
        ),
        migrations.AddField(
            model_name='viaje',
            name='precio_total_acordado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Precio Total Acordado'),
        ),
    ]
