# Generated by Django 4.2.29 on 2026-04-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_gasto_pago_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='cantidad_canastillas_colores',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='cantidad_canastillas_negras',
        ),
        migrations.RemoveField(
            model_name='viaje',
            name='kg_bruto',
        ),
        migrations.CreateModel(
            name='PesadaViaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_canastillas', models.PositiveIntegerField(default=0, verbose_name='Número de canastillas')),
                ('tipo_canastilla', models.CharField(choices=[('negra', 'Negra (1.6 kg c/u)'), ('color', 'Color (2.2 kg c/u)')], default='negra', max_length=10, verbose_name='Tipo de canastilla')),
                ('kg_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Bruto')),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='core.viaje', verbose_name='Viaje')),
            ],
            options={
                'verbose_name': 'Pesada',
                'verbose_name_plural': 'Pesadas',
                'ordering': ['id'],
            },
        ),
    ]
