# Generated by Django 4.2.29 on 2026-04-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_viaje_cantidad_canastillas_colores_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pesadaviaje',
            name='num_canastillas',
        ),
        migrations.RemoveField(
            model_name='pesadaviaje',
            name='tipo_canastilla',
        ),
        migrations.AddField(
            model_name='pesadaviaje',
            name='num_canastillas_colores',
            field=models.PositiveIntegerField(default=0, verbose_name='Canastillas Color (2.2 kg)'),
        ),
        migrations.AddField(
            model_name='pesadaviaje',
            name='num_canastillas_negras',
            field=models.PositiveIntegerField(default=0, verbose_name='Canastillas Negras (1.6 kg)'),
        ),
    ]
