# Generated by Django 4.2.30 on 2026-04-24 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_pesadaviaje_num_canastillas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleinventario',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='detalleventacredito',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoriagasto', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='loteclasificacion',
            name='clasificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='ventacredito',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ventacredito',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_credito', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ventaefectivo',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_efectivo', to='core.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AlterField(
            model_name='ventaefectivo',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_efectivo', to='core.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='ventaefectivo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_efectivo', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='viajes', to='core.proveedor', verbose_name='Proveedor'),
        ),
    ]
