# Generated by Django 4.2.30 on 2026-04-25 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_detalleinventario_clasificacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventaefectivo',
            name='clasificacion',
        ),
        migrations.RemoveField(
            model_name='ventaefectivo',
            name='kg_vendido',
        ),
        migrations.RemoveField(
            model_name='ventaefectivo',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='ventaefectivo',
            name='precio_por_kg',
        ),
        migrations.RemoveField(
            model_name='ventaefectivo',
            name='producto',
        ),
        migrations.CreateModel(
            name='DetalleVentaEfectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg_vendido', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg vendido')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por kg')),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clasificacion', verbose_name='Clasificación')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='core.ventaefectivo', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta Efectivo',
                'verbose_name_plural': 'Detalles de Ventas Efectivo',
            },
        ),
    ]
