# Generated by Django 4.2.30 on 2026-04-25 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_ventaefectivo_clasificacion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleInventario',
        ),
        migrations.DeleteModel(
            name='LiquidacionInventario',
        ),
    ]
