# Generated by Django 4.2.30 on 2026-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_detalleinventario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(unique=True, verbose_name='Inicio de Semana (Lunes)')),
                ('initial_inventory_kg', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Inventario Inicial (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Inventario Semanal',
                'verbose_name_plural': 'Inventarios Semanales',
                'ordering': ['-week_start'],
                'indexes': [models.Index(fields=['week_start'], name='core_weekly_week_st_6504bf_idx')],
            },
        ),
    ]
