# Generated by Django 4.2.30 on 2026-05-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_weeklyinventory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventacredito',
            name='fecha_vencimiento',
        ),
        migrations.RemoveField(
            model_name='ventacredito',
            name='observaciones',
        ),
    ]
