# Generated by Django 4.2.30 on 2026-05-24 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_weeklyinventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg')),
                ('precio_por_kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio por Kg')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_inventario', to='core.clasificacion', verbose_name='Clasificación')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas_inventario', to='core.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Entrada de Inventario',
                'verbose_name_plural': 'Entradas de Inventario',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
