# Generated by Django 4.2.30 on 2026-05-24 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_entrada_inventario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradainventario',
            name='kg',
        ),
        migrations.AlterField(
            model_name='entradainventario',
            name='precio_por_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Precio por Kg'),
        ),
        migrations.CreateModel(
            name='PesadaEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_canastillas_negras', models.PositiveIntegerField(default=0, verbose_name='Canastillas Negras (1.6 kg)')),
                ('num_canastillas_colores', models.PositiveIntegerField(default=0, verbose_name='Canastillas Color (2.2 kg)')),
                ('kg_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg Bruto')),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesadas', to='core.entradainventario', verbose_name='Entrada')),
            ],
            options={
                'verbose_name': 'Pesada de Entrada',
                'verbose_name_plural': 'Pesadas de Entrada',
                'ordering': ['id'],
            },
        ),
    ]
