# Generated by Django 4.2.30 on 2026-05-24 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_pesada_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaefectivo',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas_efectivo', to='core.producto', verbose_name='Producto'),
        ),
        migrations.AddField(
            model_name='ventaefectivo',
            name='total_dia',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Total del día'),
        ),
    ]
