# Generated by Django 4.2.30 on 2026-05-24 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_ventaefectivo_producto_ventaefectivo_total_dia'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg desechados')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desechos', to='core.clasificacion', verbose_name='Clasificación')),
            ],
            options={
                'verbose_name': 'Desecho de Inventario',
                'verbose_name_plural': 'Desechos de Inventario',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
