# Generated by Django 4.2.30 on 2026-05-30 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_ventacredito_fecha_vencimiento_and_more'),
        ('core', '0017_desechoinventario'),
    ]

    operations = [
    ]
