# Generated by Django 4.2.30 on 2026-06-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_gasto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventaefectivo',
            name='kg_vendido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg vendidos del día'),
        ),
    ]
