# Generated by Django 4.2.30 on 2026-06-27 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_ventaefectivo_kg_vendido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesadaviaje',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pesadas', to='core.clasificacion', verbose_name='Clasificación'),
        ),
    ]
