# Generated by Django 4.2.30 on 2026-07-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_pesadaviaje_clasificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='kg_podridos',
        ),
        migrations.AddField(
            model_name='pesadaviaje',
            name='kg_podridos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Kg Podridos / Rechazo'),
        ),
    ]
