# Generated by Django 4.2.30 on 2026-07-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_ventacredito_fecha_vencimiento_and_more'),
        ('core', '0022_remove_viaje_kg_podridos_pesadaviaje_kg_podridos'),
    ]

    operations = [
    ]
