# Generated by Django 4.2.30 on 2026-07-15 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_merge_20260714_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='desechoinventario',
            name='viaje',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='desechos', to='core.viaje', verbose_name='Viaje'),
        ),
    ]
