# Generated by Django 4.2.30 on 2026-07-15 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_desecho_inventario_viaje_fk'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='clasificacion',
            constraint=models.CheckConstraint(check=models.Q(('stock_kg__gte', 0)), name='stock_kg_no_negativo'),
        ),
    ]
