# Generated by Django 4.2.30 on 2026-07-15 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_stock_kg_no_negativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesechoLocal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('kg', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kg')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Desecho Local',
                'verbose_name_plural': 'Desechos Locales',
                'ordering': ['-fecha', '-created_at'],
            },
        ),
    ]
