# Generated by Django 4.2.30 on 2026-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_desecho_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='productos',
            field=models.ManyToManyField(related_name='viajes_m2m', to='core.producto', verbose_name='Productos adicionales'),
        ),
    ]
