# Generated by Django 4.2.30 on 2026-07-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_viaje_productos_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesadaentrada',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clasificacion', verbose_name='Clasificación'),
        ),
    ]
