# Generated by Django 4.2.30 on 2026-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_viaje_precio_por_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='tipo',
            field=models.CharField(choices=[('normal', 'Normal'), ('al_corte', 'Al corte')], default='normal', max_length=10, verbose_name='Tipo de viaje'),
        ),
    ]
