# Generated by Django 4.2.30 on 2026-08-15 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_viaje_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True, verbose_name='Fecha')),
                ('efectivo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Efectivo')),
                ('abonos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Cobro de crédito')),
                ('kg_credito', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kg a crédito')),
                ('kg_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Kg total vendido')),
                ('ventas_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total de ventas')),
                ('por_cobrar', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Total a cobrar')),
                ('gastos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Gastos')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Balance')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'Resumen diario',
                'verbose_name_plural': 'Resúmenes diarios',
                'ordering': ['-fecha'],
            },
        ),
    ]
