# Generated by Django 4.2.30 on 2026-09-15 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_resumendiario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventacredito',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='core.cliente', verbose_name='Cliente'),
        ),
    ]
